### ISSUE TITLE
[Minor] Issue with project opening 

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#16] opened 2013-07-12 11:41 UTC
At first, i tried to use a "clone to esctop" button, but github app returned me an error like this: http://clip2net.com/s/5nynJB
I assume, something is wrong with settings, because i definitely have internet connection :)

Then, i tried "download zip", but after opening, i saw that wp7 projects are not loaded. I removed and added project again (Toolkit WP7) , and got this error: http://clip2net.com/s/5nyrdW

**Comment by pedrolamas** [comment] 2013-07-12 12:40
That's due to some missing packages when a new repo is just cloned.
Rebuilding the WP8 projects should make NuGet install the missing packages, so try rebuilding them, then close the solution and reopen it and check again.

**Comment by ghost** [comment] 2013-07-12 18:54
Well.. tried to rebuild whole solution, got this: http://clip2net.com/s/5nIfAK
After that, i reopened project, got pretty the same result.

**Comment by pedrolamas** [comment] 2013-07-12 20:11
The "MSTestFramework" error tells me you're Visual Studio is not up to date! Download and install the Visual Studio 2012 Update 3 [here](http://go.microsoft.com/fwlink/?LinkID=290979).

**Comment by ghost** [comment] 2013-07-13 09:10
Ok, would do it. 
I guess, it would be nice to mention that on the front page. :)

**Comment by ghost** [comment] 2013-07-13 11:53
Well.. after updating and rebuilding, "packages" folder appeared (StyleCop.MSBuild.4.7.44.1 and WPtoolkit.4.2012.10.30 are inside), but i'm still having the same problems with opening wp7 projects.

**Comment by pedrolamas** [comment] 2013-07-13 16:08
Does your Visual Studio have NuGet package manager installed? Did you activate the package restore option in the settings?
I'd assumed these are common development settings in any Visual Studio installation (along with keeping it up to date) but I guess in the end you're right and I should have pointed this all out in the front page! :)

**Comment by ghost** [comment] 2013-07-13 17:42
1) Yep, sure. 
2) Hm..  i looked here: 
// Tools-> Options-> Package Manager-> General : "Package Restore : Allow NuGet to download missing packages during build".
I had that checkbox (i didnt do it manually before, so it is checked by default).

I guess, it would be nice to have some basic instructions, at least for those, who are looking for sources, "just in case" (c). :)

**Comment by xperiandri** [comment] 2013-07-22 19:51
So, the problem is that WP7 projects depend on BCL.Build
But as long as Visual Studio can't load them it can't find that they depend on that package :)
Recursive dependency

So, @PedroLamas you can add BCL.Build to source control (at least critical files) or update BCL.Build dependency to the latest version please, so we can install it from NuGet repository.

**Comment by jeffwilcox** [comment] 2013-07-22 20:23
Isn't there a way to enable msbuild to pull in nuget packages that it needs?

Sent from my Windows Phone

**Comment by pedrolamas** [comment] 2013-07-22 20:30
I don't see the point in adding the NuGet packages directly, all that it's needed it to pre-install the packages, so... I've added a "setup" option to the build process!

Just open a PowerShell window, enter the "build" folder, and run

```
.\psake.ps1 setup
```

**Comment by pedrolamas** [comment] 2013-07-22 20:32
@jeffwilcox yep, but given I already use PowerShell to build and create the packages, I think it's also a nice way to setup the environment... also, I think that using PowerShell seems a bit more "future prone" for situations like this!

**Comment by jeffwilcox** [comment] 2013-07-22 20:42
Sounds like the right solution, cool.

**Comment by pedrolamas** [comment] 2013-07-29 12:55
@VeTaLNearga have you been able to open the project using the indicated solution?

**Comment by pedrolamas** [comment] 2013-08-13 15:01
Closing this as not further contact has been established!

**Closed as completed by pedrolamas** 2013-08-13 15:01 UTC

**Comment by rikkit** [comment] 2013-08-13 16:14
For what it's worth Pedro i had the same problem as the op and your powershell fixed it.
